# Dependabot Configuration - Automated Dependency Updates
# Keeps your dependencies up-to-date and secure

version: 2
updates:
  # Enable version updates for Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Lamont-Labs"
    assignees:
      - "Lamont-Labs"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "build"
      include: "scope"
    # Group updates by type
    groups:
      android:
        patterns:
          - "androidx.*"
          - "com.google.android.*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.kotlinx*"
      testing:
        patterns:
          - "*junit*"
          - "*test*"
          - "*mockito*"
      ml:
        patterns:
          - "org.tensorflow*"
          - "org.opencv*"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "org.jetbrains.kotlin:kotlin-gradle-plugin"
        update-types: ["version-update:semver-major"]
      - dependency-name: "com.android.tools.build:gradle"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "Lamont-Labs"
    assignees:
      - "Lamont-Labs"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
