# Funding options for QuantraVision
# Update these with your actual profiles

github: # [yourusername]
patreon: # quantravision
ko_fi: # lamontlabs
custom: ['https://lamontlabs.com/support', 'https://buymeacoffee.com/quantravision']
