workflows:
  quantravision-android:
    name: QuantraVision Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    
    environment:
      # Android code signing (optional - upload keystore to Codemagic for signed builds)
      android_signing:
        - quantravision_keystore
      
      # Environment variable groups (configure in Codemagic UI if needed)
      groups:
        - google_play  # Optional: for Google Play publishing
      
      # Project-specific variables
      vars:
        PACKAGE_NAME: "com.lamontlabs.quantravision"
        # Gradle JVM settings for large build (OpenCV + TensorFlow Lite)
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dkotlin.daemon.jvm.options=-Xmx4g"
      
      java: 17  # JDK 17 required for AGP 8.7.3
    
    # Caching to speed up subsequent builds
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        - $HOME/.android/build-cache
        - $HOME/.konan
    
    # Build triggers
    triggering:
      events:
        - push
        - pull_request
        - tag
      branch_patterns:
        - pattern: "main"
          include: true
        - pattern: "develop"
          include: true
        - pattern: "release/*"
          include: true
    
    scripts:
      # 1. System diagnostics and environment check
      - name: System diagnostics
        script: | 
          echo "═══════════════════════════════════════════════════════════"
          echo "CODEMAGIC BUILD DIAGNOSTICS - QuantraVision"
          echo "═══════════════════════════════════════════════════════════"
          echo "Build number: $BUILD_NUMBER"
          echo "Branch: $CM_BRANCH"
          echo "Commit: $CM_COMMIT"
          echo "───────────────────────────────────────────────────────────"
          echo "Java version:"
          java -version
          echo "───────────────────────────────────────────────────────────"
          echo "Android SDK location: $ANDROID_SDK_ROOT"
          echo "Available SDK platforms:"
          ls -la $ANDROID_SDK_ROOT/platforms/ 2>/dev/null || echo "No platforms found"
          echo "───────────────────────────────────────────────────────────"
          echo "Disk space:"
          df -h | grep -E "Filesystem|/dev/"
          echo "───────────────────────────────────────────────────────────"
          echo "Memory:"
          free -h || vm_stat
          echo "═══════════════════════════════════════════════════════════"
      
      # 2. Set up Android SDK location
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          cat "$CM_BUILD_DIR/local.properties"
      
      # 3. Make gradlew executable
      - name: Make gradlew executable
        script: | 
          chmod +x gradlew
          ls -la gradlew
      
      # 4. Clean and verify Gradle setup (auto-fix)
      - name: Gradle setup and dependency resolution
        script: | 
          echo "Cleaning previous builds..."
          ./gradlew clean --stacktrace || echo "Clean failed, continuing..."
          
          echo "Verifying Gradle daemon..."
          ./gradlew --status || echo "No daemon running"
          
          echo "Resolving dependencies with retry logic..."
          retry_count=0
          max_retries=3
          until ./gradlew dependencies --refresh-dependencies --stacktrace || [ $retry_count -eq $max_retries ]; do
            retry_count=$((retry_count+1))
            echo "Dependency resolution attempt $retry_count failed, retrying..."
            sleep 5
            # Kill any stuck Gradle daemons
            ./gradlew --stop || true
          done
          
          echo "Dependencies resolved successfully!"
      
      # 5. Run lint checks (optional - won't block build)
      - name: Run Android Lint
        script: | 
          ./gradlew lintDebug --stacktrace || echo "Lint check failed, continuing with build..."
        ignore_failure: true
      
      # 6. Run unit tests (optional)
      - name: Run unit tests
        script: | 
          ./gradlew test --stacktrace || echo "Tests failed, continuing with build..."
        test_report: app/build/test-results/**/*.xml
        ignore_failure: true
      
      # 7. Build debug APK with auto-retry on failure
      - name: Build debug APK (with auto-retry)
        script: | 
          echo "Building debug APK..."
          retry_count=0
          max_retries=3
          
          until ./gradlew assembleDebug --stacktrace --info || [ $retry_count -eq $max_retries ]; do
            retry_count=$((retry_count+1))
            echo "═══════════════════════════════════════════════════════════"
            echo "Build attempt $retry_count failed. Auto-diagnosing..."
            echo "═══════════════════════════════════════════════════════════"
            
            # Check for common issues and auto-fix
            if grep -q "OutOfMemoryError" app/build/outputs/logs/* 2>/dev/null; then
              echo "⚠️  Detected: Out of memory error"
              echo "Fixing: Killing Gradle daemons and increasing heap..."
              ./gradlew --stop
              export GRADLE_OPTS="$GRADLE_OPTS -Xmx8g"
              
            elif grep -q "Could not resolve" app/build/outputs/logs/* 2>/dev/null; then
              echo "⚠️  Detected: Dependency resolution failure"
              echo "Fixing: Refreshing dependencies..."
              ./gradlew --refresh-dependencies
              
            elif grep -q "Daemon" app/build/outputs/logs/* 2>/dev/null; then
              echo "⚠️  Detected: Gradle daemon issue"
              echo "Fixing: Stopping all daemons..."
              ./gradlew --stop
              pkill -f GradleDaemon || true
              
            else
              echo "⚠️  Generic build failure detected"
              echo "Fixing: Cleaning build cache and retrying..."
              ./gradlew clean --stacktrace
              rm -rf ~/.gradle/caches/build-cache-*
            fi
            
            echo "Retrying build (attempt $((retry_count+1))/$max_retries)..."
            sleep 10
          done
          
          # Final check
          if [ ! -f app/build/outputs/apk/debug/*.apk ]; then
            echo "❌ ERROR: Debug APK not found after $max_retries attempts"
            echo "Last build log:"
            cat app/build/outputs/logs/* 2>/dev/null || echo "No logs available"
            exit 1
          fi
          
          echo "✅ Debug APK built successfully!"
          ls -lh app/build/outputs/apk/debug/*.apk
      
      # 8. Build release APK with auto-retry
      - name: Build release APK (with auto-retry)
        script: | 
          echo "Building release APK..."
          retry_count=0
          max_retries=2
          
          until ./gradlew assembleRelease --stacktrace || [ $retry_count -eq $max_retries ]; do
            retry_count=$((retry_count+1))
            echo "Release build attempt $retry_count failed, retrying..."
            ./gradlew --stop
            ./gradlew clean
            sleep 5
          done
          
          if [ -f app/build/outputs/apk/release/*.apk ]; then
            echo "✅ Release APK built successfully!"
            ls -lh app/build/outputs/apk/release/*.apk
          else
            echo "⚠️  Release APK build failed, but debug APK succeeded"
          fi
        ignore_failure: true
      
      # 9. Build release bundle (AAB) for Google Play (optional)
      - name: Build release bundle (AAB)
        script: | 
          echo "Building release AAB for Google Play..."
          ./gradlew bundleRelease \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=1.0.$BUILD_NUMBER \
            --stacktrace || echo "AAB build failed (requires signing config)"
          
          if [ -f app/build/outputs/bundle/release/*.aab ]; then
            echo "✅ Release AAB built successfully!"
            ls -lh app/build/outputs/bundle/release/*.aab
          fi
        ignore_failure: true
      
      # 10. Build summary report
      - name: Build summary
        script: | 
          echo "═══════════════════════════════════════════════════════════"
          echo "BUILD SUMMARY - QuantraVision"
          echo "═══════════════════════════════════════════════════════════"
          echo "Debug APK:"
          ls -lh app/build/outputs/apk/debug/*.apk 2>/dev/null && echo "✅ SUCCESS" || echo "❌ FAILED"
          echo "───────────────────────────────────────────────────────────"
          echo "Release APK:"
          ls -lh app/build/outputs/apk/release/*.apk 2>/dev/null && echo "✅ SUCCESS" || echo "⚠️  SKIPPED/FAILED"
          echo "───────────────────────────────────────────────────────────"
          echo "Release AAB:"
          ls -lh app/build/outputs/bundle/release/*.aab 2>/dev/null && echo "✅ SUCCESS" || echo "⚠️  SKIPPED/FAILED"
          echo "═══════════════════════════════════════════════════════════"
          echo "Build completed at: $(date)"
          echo "═══════════════════════════════════════════════════════════"
    
    # Collect all build outputs
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      - app/build/outputs/mapping/release/mapping.txt  # ProGuard mapping
      - app/build/reports/**  # Lint and test reports
    
    # Build notifications and publishing
    publishing:
      # Email notifications
      email:
        recipients:
          - Lamontlabs@proton.me
        notify:
          success: true
          failure: true
      
      # Slack notifications (optional)
      # slack:
      #   channel: '#builds'
      #   notify_on_build_start: false
      #   notify:
      #     success: true
      #     failure: true
      
      # Google Play Store publishing (optional - requires setup)
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: internal  # Options: internal, alpha, beta, production
      #   submit_as_draft: true
      #   in_app_update_priority: 3
      #   rollout_fraction: 0.25
      #   changes_not_sent_for_review: false

  # Quick debug build workflow (faster, no signing/publishing)
  quantravision-quick:
    name: QuantraVision Quick Build
    max_build_duration: 60
    instance_type: linux_x2
    
    environment:
      vars:
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g"
      java: 17
    
    cache:
      cache_paths:
        - $HOME/.gradle/caches
    
    scripts:
      - name: Set Android SDK
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      
      - name: Build debug APK
        script: | 
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
    
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    
    publishing:
      email:
        recipients:
          - Lamontlabs@proton.me
        notify:
          success: true
          failure: true
