package com.lamontlabs.quantravision.apex.protocols.learning.mobile

typealias LP16ConfidenceModifierCalculator = com.lamontlabs.quantravision.apex.protocols.learning.LP16ConfidenceModifierCalculator
