name: ðŸ› Bug Report
description: Report a bug or unexpected behavior in QuantraVision
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - Lamont-Labs

body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for reporting a bug!
        
        Please fill out this form as completely as possible to help us reproduce and fix the issue quickly.
        
        **Before submitting:**
        - Search [existing issues](https://github.com/Lamont-Labs/QuantraVision/issues) to avoid duplicates
        - Update to the latest version of QuantraVision
        - Check the [FAQ](https://github.com/Lamont-Labs/QuantraVision/wiki/FAQ) for known issues

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "Example: Pattern detection overlay freezes when scanning TradingView charts..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Open QuantraVision app
        2. Grant overlay permission
        3. Navigate to TradingView
        4. Tap "Start Detection"
        5. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "Pattern detection should run smoothly without freezing..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Overlay freezes and becomes unresponsive..."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: QuantraVision Version
      description: Which version are you using? (Settings â†’ About)
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: android-version
    attributes:
      label: Android Version
      description: What version of Android are you running?
      options:
        - Android 15 (API 35)
        - Android 14 (API 34)
        - Android 13 (API 33)
        - Android 12 (API 31-32)
        - Android 11 (API 30)
        - Android 10 (API 29)
        - Android 9 (API 28)
        - Android 8 (API 26-27)
        - Android 7 (API 24-25)
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device Model
      description: What device are you using?
      placeholder: "Google Pixel 8 Pro, Samsung Galaxy S24, OnePlus 12, etc."
    validations:
      required: true

  - type: dropdown
    id: tier
    attributes:
      label: Subscription Tier
      description: Which tier are you using?
      options:
        - Free Tier
        - Standard ($14.99)
        - Pro ($29.99)
        - Trading Book Only ($2.99)
    validations:
      required: true

  - type: dropdown
    id: trading-app
    attributes:
      label: Trading App Used
      description: Which trading app were you using when the bug occurred?
      options:
        - TradingView
        - Webull
        - Robinhood
        - TD Ameritrade
        - Interactive Brokers
        - MetaTrader 4/5
        - Other (specify in additional context)
        - N/A (not app-specific)
    validations:
      required: false

  - type: dropdown
    id: frequency
    attributes:
      label: Bug Frequency
      description: How often does this bug occur?
      options:
        - Always (100%)
        - Frequently (>50%)
        - Sometimes (10-50%)
        - Rarely (<10%)
        - Once
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: |
        If applicable, provide error logs from Android Logcat (Settings â†’ Advanced â†’ Export Debug Logs).
        Wrap logs in triple backticks (```) for readability.
      placeholder: |
        ```
        2025-11-02 14:23:45.123 E/QuantraVision: java.lang.OutOfMemoryError
            at com.lamontlabs.quantravision.detection.Detector.analyze(Detector.kt:45)
        ```
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Screen Recording
      description: |
        Drag and drop screenshots or screen recordings here.
        Visual evidence significantly helps diagnose UI/UX issues.
      placeholder: "Drag images/videos here..."

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Have you found any temporary workaround for this issue?
      placeholder: "Restarting the app temporarily fixes the issue..."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context that might help us understand the issue.
      placeholder: |
        - Does this happen only with specific patterns?
        - RAM usage at time of crash?
        - Any recent system updates?

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-Submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched for similar issues and found none
          required: true
        - label: I am using the latest version of QuantraVision
          required: true
        - label: I have provided all required information above
          required: true
        - label: I have attached screenshots/logs if applicable
          required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        **Privacy Note:** This issue tracker is public. Do not share sensitive personal information, API keys, or financial data.
        
        **Thank you for helping improve QuantraVision!** We aim to respond to all bug reports within 48 hours.
