name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.10.2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew clean assembleDebug --stacktrace --no-daemon

      - name: Run Lint
        run: ./gradlew lintDebug --stacktrace --no-daemon

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace --no-daemon
