name: Android CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7
          cache-read-only: false

      - name: Build Debug, Lint, Unit tests
        run: ./gradlew assembleDebug lint test || gradle assembleDebug lint test

      - name: Upload Debug artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qv-debug-outputs
          path: |
            app/build/outputs/apk/debug/**/*.apk
            app/build/reports/**

  bundle-release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7
          cache-read-only: false

      - name: Assemble Release AAB
        run: ./gradlew bundleRelease || gradle bundleRelease

      - name: Upload Release bundle
        uses: actions/upload-artifact@v4
        with:
          name: qv-release-aab
          path: app/build/outputs/bundle/release/*.aab
